# Egeria Settings
egeria:
  # Global Egeria Settings
  logging: error
  version: "3.5"
  debug: true

  # persistence
  persistence: true
  storageClass: ibmc-vpc-block-10iops-tier
  storageSize: 8Gi
  repositoryType: "local-graph-repository"

  # communication
  cohort: mds
  viewOrg: org
  kafkaEndpoint: egeria-kafka:9092

  # userid used for admin ops (no security enabled by default)
  user: garygeeke

  # list of servers that should start on this platform
  # the names must correspond to a config-<name>.sh script
  # as well as to the actual instance name
  serverList: mds1,view1

  # OMAG Server
  # usually you need to configure a connection to an OMAG server
  # the values below will result in EGERIA_OMAG_SERVER_NAME and EGERIA_OMAG_SERVER_URL environment variables
  # if platformUrl is empty this will point to itself
  omagServer:
    name: mds1
    platformUrl: ""
    

# Additional environment variables that are needed for setup the servers
extraEnv: {}

# name a secret to mount as environment variables to store secrets
secretName: ""

replicaCount: 1

image:
  repository: quay.io/odpi/egeria
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.5-SNAPSHOT"
  
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 0

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  platformPort: 9443
  debugPort: 5005

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1
    memory: 700Mi
  requests:
    cpu: 1
    memory: 700Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
